@PORT = 3000

@HOST = http://localhost:{{PORT}}

###AUTORES
GET {{HOST}}/api/autores
Authorization: API-KEY
###
GET {{HOST}}/api/autores/2
Authorization: API-KEY
###
POST {{HOST}}/api/autores
Authorization: API-KEY
Content-Type: application/json

{
    "nombre": "Marta Mendoza",
    "email": "marta.mendoza@example.com",
    "imagen": "autora3.jpg"
}
###
PUT {{HOST}}/api/autores/2
Authorization: API-KEY
Content-Type: application/json

{
    "nombre": "AutorEditado",
    "email": "emailEditado@example.com",
    "imagen": "imagen.jpg"
}

###
DELETE {{HOST}}/api/autores/5
Authorization: API-KEY


###POSTS
GET {{HOST}}/api/posts
Authorization: API-KEY
###
GET {{HOST}}/api/posts/3
Authorization: API-KEY
###
POST {{HOST}}/api/posts
Authorization: API-KEY
Content-Type: application/json

{
    "titulo": "Nuevo post agregado",
    "descripcion": "Este post incluyendo la inteligencia artificial, el aprendizaje automático y la computación en la nube.",
    "fecha_creacion": "2024-06-01 12:00:00",
    "categoria": "Tecnología",
    "autor_id": "3"
}
###
PUT {{HOST}}/api/posts/2
Authorization: API-KEY
Content-Type: application/json

{
    "titulo": "El futuro está aquí: si atendemos a las rutinas diarias",
    "descripcion": "Este post discute la necesidad de tener rutinas que nos ayuden a mejorar nuestra calidad de vida.",
    "fecha_creacion": "2024-06-04 13:00:00",
    "categoria": "Rutinas",
    "autor_id": "3"
}

###
DELETE {{HOST}}/api/posts/18
Authorization: API-KEY